# Generated by Django 6.0 on 2025-12-30 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(default='0000', max_length=20, verbose_name='Matrícula/Registro')),
                ('cargo', models.CharField(default='Colaborador', max_length=50, verbose_name='Função/Cargo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
