# Generated by Django 6.0 on 2025-12-31 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('senso', models.CharField(choices=[('SEIRI', '1. Seiri (Utilização)'), ('SEITON', '2. Seiton (Ordenação)'), ('SEISO', '3. Seiso (Limpeza)'), ('SEIKETSU', '4. Seiketsu (Padronização)'), ('SHITSUKE', '5. Shitsuke (Disciplina)')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pergunta do Checklist',
                'verbose_name_plural': 'Perguntas do Checklist',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('PRODUCAO', 'Produção'), ('ALMOXARIFADO', 'Almoxarifado'), ('MANUTENCAO', 'Manutenção'), ('ESCRITORIO', 'Escritório/Adm')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conforme', models.BooleanField(default=False, verbose_name='Está conforme?')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='auditorias/', verbose_name='Evidência (Foto)')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualidade.auditoria')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualidade.questao')),
            ],
        ),
    ]
